/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface EvidenceRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addEvidence"
      | "evidenceCount"
      | "getEvidence"
      | "transferCustody"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "CustodyTransferred" | "EvidenceAdded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addEvidence",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "evidenceCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEvidence",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferCustody",
    values: [BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "addEvidence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "evidenceCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEvidence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferCustody",
    data: BytesLike
  ): Result;
}

export namespace CustodyTransferredEvent {
  export type InputTuple = [
    evidenceId: BigNumberish,
    oldOwner: AddressLike,
    newOwner: AddressLike
  ];
  export type OutputTuple = [
    evidenceId: bigint,
    oldOwner: string,
    newOwner: string
  ];
  export interface OutputObject {
    evidenceId: bigint;
    oldOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EvidenceAddedEvent {
  export type InputTuple = [
    evidenceId: BigNumberish,
    fileHash: BytesLike,
    owner: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    evidenceId: bigint,
    fileHash: string,
    owner: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    evidenceId: bigint;
    fileHash: string;
    owner: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EvidenceRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): EvidenceRegistry;
  waitForDeployment(): Promise<this>;

  interface: EvidenceRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addEvidence: TypedContractMethod<
    [_fileHash: BytesLike],
    [void],
    "nonpayable"
  >;

  evidenceCount: TypedContractMethod<[], [bigint], "view">;

  getEvidence: TypedContractMethod<
    [_evidenceId: BigNumberish],
    [
      [string, string, bigint] & {
        fileHash: string;
        owner: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  transferCustody: TypedContractMethod<
    [_evidenceId: BigNumberish, _newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addEvidence"
  ): TypedContractMethod<[_fileHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "evidenceCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEvidence"
  ): TypedContractMethod<
    [_evidenceId: BigNumberish],
    [
      [string, string, bigint] & {
        fileHash: string;
        owner: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferCustody"
  ): TypedContractMethod<
    [_evidenceId: BigNumberish, _newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "CustodyTransferred"
  ): TypedContractEvent<
    CustodyTransferredEvent.InputTuple,
    CustodyTransferredEvent.OutputTuple,
    CustodyTransferredEvent.OutputObject
  >;
  getEvent(
    key: "EvidenceAdded"
  ): TypedContractEvent<
    EvidenceAddedEvent.InputTuple,
    EvidenceAddedEvent.OutputTuple,
    EvidenceAddedEvent.OutputObject
  >;

  filters: {
    "CustodyTransferred(uint256,address,address)": TypedContractEvent<
      CustodyTransferredEvent.InputTuple,
      CustodyTransferredEvent.OutputTuple,
      CustodyTransferredEvent.OutputObject
    >;
    CustodyTransferred: TypedContractEvent<
      CustodyTransferredEvent.InputTuple,
      CustodyTransferredEvent.OutputTuple,
      CustodyTransferredEvent.OutputObject
    >;

    "EvidenceAdded(uint256,bytes32,address,uint256)": TypedContractEvent<
      EvidenceAddedEvent.InputTuple,
      EvidenceAddedEvent.OutputTuple,
      EvidenceAddedEvent.OutputObject
    >;
    EvidenceAdded: TypedContractEvent<
      EvidenceAddedEvent.InputTuple,
      EvidenceAddedEvent.OutputTuple,
      EvidenceAddedEvent.OutputObject
    >;
  };
}
